info:
  contact: {}
  title: 毛球社区
paths:
  /v1/user/deleteUser/{id}:
    delete:
      consumes:
      - application/json
      description: 通过id，删除用户 eg：{ "id":"7"}
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除用户
  /v1/user/getUserList:
    get:
      consumes:
      - application/json
      description: 获取所有用户信息
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取用户列表
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: 通过id和pw登录 eg：{ "account":"wbq", "password":"123" }
      parameters:
      - description: account+password
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户登录
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: 注册一个新的用户 eg：{ "account":"wbq", "password":"123" }
      parameters:
      - description: account+password
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户注册
  /v1/user/updatePassword/{id}:
    put:
      consumes:
      - application/json
      description: 通过id，修改密码 eg：{"password":"123" }
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: new_pwd
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: 更改密码
  /v1/user/updateUsername/{id}:
    put:
      consumes:
      - application/json
      description: 通过id，修改用户名 eg：{"username":"wangwang" }
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: new_name
        in: body
        name: user
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 更改用户名
swagger: "2.0"
